name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build and Package with Maven
        run: mvn -B clean package -DfinalName=mi-aplicacion --file pom.xml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Check if ECR repository exists
        id: ecr-check
        continue-on-error: true
        run: |
          REPO_NAME="mi-aplicacion-repo"
          aws ecr describe-repositories --repository-names $REPO_NAME

      - name: Create ECR repository if not exists
        if: steps.ecr-check.outcome == 'failure'
        run: |
          REPO_NAME="mi-aplicacion-repo"
          aws ecr create-repository --repository-name $REPO_NAME

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: List files in workspace
        run: ls -la

      - name: Copy JAR to workspace root
        run: cp target/mi-aplicacion.jar mi-aplicacion.jar

      - name: Build Docker Image
        run: docker build -t mi-aplicacion .

      - name: Tag Docker image
        run: docker tag mi-aplicacion:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.sa-east-1.amazonaws.com/mi-aplicacion-repo:latest

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.sa-east-1.amazonaws.com/mi-aplicacion-repo:latest